version: '3.1'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    privileged: true
    ports:
      - 2181:2181
    volumes:
      - ./zk/conf:/conf
      - ./zk/data:/data

  otter-manager:
    container_name: otter-manager
    image: otter-manager:4.2.18
    restart: always
    privileged: true
    environment:
      DOMAIN_NAME: 192.168.0.120
      OTTER_PORT: 8081
      OTTER_MANAGER_MYSQL: 192.168.0.120:3306
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: suntek
      COMMUNICATION_MANAGER_PORT: 1099
      ZOOKEEPER_CLUSTER_DEFAULT: 192.168.0.120:2181
    ports:
      - 8081:8081
      - 1099:1099
    volumes:
      - ./otter-manager/conf:/usr/local/otter/conf
      - ./otter-manager/logs:/usr/local/otter/logs

